FROM nvidia/cuda:9.0-base-ubuntu16.04

LABEL maintainer="volker.hilsenstein@monash.edu"

RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        cuda-command-line-tools-8-0 \
        cuda-cublas-dev-8-0 \
        cuda-cudart-dev-8-0 \
        cuda-cufft-dev-8-0 \
        cuda-curand-dev-8-0 \
        cuda-cusolver-dev-8-0 \
        cuda-cusparse-dev-8-0 \
        curl \
        git \
        libtiff-dev \ 
        libx11-6 \
        libzmq3-dev \
        libfftw3-dev \
        libboost-filesystem1.58.0\
        libboost-filesystem1.58-dev\
        libboost-system1.58.0\
        libboost-system1.58-dev\
        libboost-program-options1.58.0\
        libboost-program-options1.58-dev\
        libboost1.58-dev \
        pkg-config \
        python-dev \
        rsync \
        software-properties-common \
        unzip \
        zip \
        zlib1g-dev \
       