FROM nvidia/cuda:9.0-base-ubuntu16.04

LABEL maintainer="Noone"

RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        cuda-command-line-tools-8-0 \
        cuda-cublas-dev-8-0 \
        cuda-cudart-dev-8-0 \
        cuda-cufft-dev-8-0 \
        cuda-curand-dev-8-0 \
        cuda-cusolver-dev-8-0 \
        cuda-cusparse-dev-8-0 \
        curl \
        git \
        libcufft8.0 \
        libcurl3-dev \
        libfreetype6-dev \
        libhdf5-serial-dev \
        libpng12-dev \
        libtiff-dev \ 
        libX11-dev \
        libzmq3-dev \
        libfftw3-dev \
        libboost1.58-dev \
        pkg-config \
        python-dev \
        rsync \
        software-properties-common \
        unzip \
        zip \
        zlib1g-dev \
        wget 